version: '3'

services:
  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/facebook_scraper

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/facebook_scraper
